apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ID}}-ingress"
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: {{SUBDOMAIN}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "{{ID}}-svc"
                port:
                  number: 80
